grade=sample(c('a','b','c','d'),size=30,replace=T,prob=c(0.4,0.2,0.3,0.1))
grade
gradef=factor(grade)
summary(gradef)
summary(grade)
class(gradef)
gradef=factor(grade,ordered=T)
class(gradef)
summary(gradef)
gradef0=factor(grade,ordered = T,levels = c('b','c','a','d'))
(marks=ceiling(rnorm(30,mean=60,sd=5)))
(gender=factor(sample(c('m','f'),size=30,replace=T)))
(student1=data.frame(marks,gradef0))
boxplot(marks ~ gradef0,data=student1)  
abline(h=summary(marks))
quantile(marks)
boxplot(marks~gradef0+gender,data=student1)
